AalConfig:
  IsCreateSpatialCalcuratorOnInit: true
  IsPoolSpeakerBalanceUnifier: true
  IsRequestLoadOnInitialize: true
  MaxEmitterCount: 360
  MemoryMgrSmallRate: 0.158000007
  OpusChannelCount: 12
  OutputVolumStereoJack: 1.0
  OutputVolumeBuildInSpeaker: 1.0
  OutputVolumeTV: 1.0
  ResourceHeapSize: 50.0
  StreamCacheBlockCountRate: 0.800000012
  StreamChannelCountMax: !u 0x00000050
  StreamReadCacheSize: 256
  SubMixCount: 11
  SubResourceHeapSize: 4.5
  UseOpus: true
ListenerSwitcherNum: 1
Listeners: []
MessageVoiceGroup: DemoDialog
SLinkConfig: {CalcRequestQueueSize: 512, EventPoolSize: 384, UserCreateHeapSize: 768}
Scenery: [Work/Sound/Scenery/None.alto__Scenery.gyml, Work/Sound/Scenery/MainField.alto__Scenery.gyml, Work/Sound/Scenery/CDungeon.alto__Scenery.gyml,
  Work/Sound/Scenery/LargeDungeon.alto__Scenery.gyml, Work/Sound/Scenery/Underground.alto__Scenery.gyml]
ShapeList:
  IsUseExperimental: false
  ShapeList:
  - Bone: ''
    FittingInterpolateRate: 1.0
    FittingInterpolateThreshold: 0.0
    FittingTarget: Auto
    IsBoundingRelative_Offset: true
    IsCustomSetup: false
    IsEnabledFittingInterpolate: false
    IsFittingActorSize: false
    IsIgnoreRotate: false
    IsOldCompatible: true
    IsSetSpreadByShapeExpands: false
    IsUseRigidBodySensor: false
    Name: Chemical_Updraft
    Offset: {X: 0.0, Y: 0.0, Z: 0.0}
    Rotate: {X: 0.0, Y: 0.0, Z: 0.0}
    RotateOrigin: {X: 0.0, Y: 0.0, Z: 0.0}
    Scale: {X: 1.0, Y: 1.0, Z: 1.0}
    SetupType: UseFittingParam
    ShapeAxis: Y
    ShapeType: Cylinder
    SpreadCoef: 1.0
    UpdateType: Attached
  - Bone: ''
    FittingInterpolateRate: 1.0
    FittingInterpolateThreshold: 0.0
    FittingTarget: Auto
    IsBoundingRelative_Offset: true
    IsCustomSetup: false
    IsEnabledFittingInterpolate: false
    IsFittingActorSize: false
    IsIgnoreRotate: false
    IsOldCompatible: true
    IsSetSpreadByShapeExpands: false
    IsUseRigidBodySensor: false
    Name: Chemical_WindCapsule
    Offset: {X: 0.0, Y: 0.0, Z: 0.0}
    Rotate: {X: 0.0, Y: 0.0, Z: 0.0}
    RotateOrigin: {X: 0.0, Y: 0.0, Z: 0.0}
    Scale: {X: 1.0, Y: 1.0, Z: 1.0}
    SetupType: UseFittingParam
    ShapeAxis: Y
    ShapeType: Capsule
    SpreadCoef: 1.0
    UpdateType: Attached
