AlwaysClient: false
AlwaysConsiderRanged: false
Attributes: []
MakesPlayerPartySizeInfinite: true
MaxAttackers: 1
PartyCreateRules: []
PartyDisbandRules: []
PartyJoinRules: [TargetCheck]
PartyMergeRules: []
PartyRadius: 0.0
PartySplitRules: []
TargetingRules: [ForceChangeRecommendationTarget]
UniqueTag: None
