{$parent: Work/Component/CaveEnvironmentParam/DeepHole_Standard.game__component__CaveEnvironmentParam.gyml, EffectCaveFadeEndDistance: 35.0,
  EffectCaveFadeStartDistance: 20.0, NameID: Work/Location/DeepHole_HyrulePlains.game__location__Location.gyml}
