{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, IsSmallCave: false,
  NameID: Work/Location/Well_0018.game__location__Location.gyml, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
