{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, FluidEffectType: FluidEffect_Cave_Dust,
  IsEnableEnv: false, IsNotAutoPlace: false, IsNotAutoSpawn: false, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
