{CavePalette: Work/WorldMgr/CavePalette/Cave_Lanayru_0040.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly, IsNotAutoPlace: true, IsNotAutoSpawn: true, NameID: '', Weather: CaveRain}
