{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Immediate, FluidEffectType: FluidEffect_Cave_Dust,
  IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_GerudoDesert_0046.game__location__Location.gyml, Temperature_DayDirect: 20.0,
  Temperature_NightDirect: 20.0}
