{EffectCaveFadeEndDistance: 40.0, EffectCaveFadeStartDistance: 20.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, NameID: Work/Location/Cave_Firone_0016.game__location__Location.gyml, Weather: CaveRain}
