AlwaysClient: false
AlwaysConsiderRanged: false
Attributes: []
MakesPlayerPartySizeInfinite: false
MaxAttackers: 3
PartyCreateRules: []
PartyDisbandRules: [TargetersCheck]
PartyJoinRules: [TargetCheck, DistanceCheck]
PartyMergeRules: [HigherPriority, Overlap]
PartyRadius: 5.0
PartySplitRules: [DistanceCheck, TargetersCheck]
TargetingRules: []
UniqueTag: Riju
