{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, FluidEffectType: FluidEffect_Cave_DustGroundOnly,
  IsNotAutoPlace: true, IsNotAutoSpawn: true, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
