{EnvPalette: Work/WorldMgr/ResEnvPalette/Prequel_MainField_Bluesky_0_Sunrise.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Normal,
  IsEnableEnv: false, IsNotAutoPlace: false, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
