{CavePalette: Work/WorldMgr/CavePalette/TabantaArid.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  EnvPaletteChangeSpeed: Normal, IsNotAutoPlace: false, NameID: Work/Location/Cave_HyruleRidge_0007.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0, Weather: Invalid}
