EffectCaveFadeEndDistance: 50.0
EffectCaveFadeStartDistance: 35.0
EnvEffect: Invalid
EnvFireLevel: 0
EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml
EnvPaletteChangeSpeed: VeryFast
IsNotAutoPlace: false
IsNotAutoSpawn: false
NameID: Work/Location/Cave_Lanayru_0052.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
