{EffectCaveFadeEndDistance: 30.0, EffectCaveFadeStartDistance: 20.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  EnvPaletteChangeSpeed: Normal, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_FirstPlateau_0002.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
