CavePalette: Work/WorldMgr/CavePalette/Eldin_Light.game__wm__CavePalette.gyml
EnvEffect: Invalid
EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml
EnvPaletteChangeSpeed: VeryFast
FluidEffectType: FluidEffect_Cave_Volcano
IsNotAutoPlace: false
IsNotAutoSpawn: true
IsNotAutoSpawn_Animal: false
IsNotAutoSpawn_Enemy: false
NameID: Work/Location/Cave_Eldin_0039.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
