{$parent: Work/Component/CaveEnvironmentParam/DeepHole_Standard.game__component__CaveEnvironmentParam.gyml, EffectCaveFadeEndDistance: 40.0,
  EffectCaveFadeStartDistance: 25.0, NameID: Work/Location/DeepHole_HimeidaMt.game__location__Location.gyml}
