{CavePalette: Work/WorldMgr/CavePalette/FiloneRemains.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, NameID: Work/Location/Cave_Firone_0020.game__location__Location.gyml}
