{EffectCaveFadeEndDistance: 20.0, EffectCaveFadeStartDistance: 5.0, FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly,
  IsNotAutoSpawn_Enemy: true, IsSmallCave: true, NameID: Work/Location/Well_0042.game__location__Location.gyml}
