{CavePalette: Work/WorldMgr/CavePalette/HyruleWell.game__wm__CavePalette.gyml, IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true,
  IsSmallCave: true, NameID: Work/Location/Well_0011.game__location__Location.gyml, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
