{CavePalette: Work/WorldMgr/CavePalette/Eldin_Light.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_HyruleForest_0006.game__location__Location.gyml}
