ActiveSound: true
CurveType:
  Default:
    Curve:
      Direct: {Max: 0.100000001, Offset: 0.0500000007, OffsetValue: 1.0}
      Filter1: {Max: 0.600000024, Offset: 0.0250000004, OffsetValue: 0.0}
      Room: {Max: 0.100000001, Offset: 0.5, OffsetValue: 1.0}
  Type1:
    Curve:
      Direct: {Max: 0.100000001, Offset: 0.200000003, OffsetValue: 0.569999993}
      Filter1: {Max: 0.600000024, Offset: 0.200000003, OffsetValue: 0.289999992}
      Room: {Max: 0.100000001, Offset: 0.5, OffsetValue: 1.0}
  Type2:
    Curve:
      Direct: {Max: 0.600000024, Offset: 0.0, OffsetValue: 1.0}
      Filter1: {Max: 0.400000006, Offset: 0.0}
      Room: {Max: 0.600000024, Offset: 0.0, OffsetValue: 1.0}
  Type3:
    Curve:
      Direct: {Max: 0.400000006, Offset: 0.0, OffsetValue: 1.0}
      Filter1: {Max: 0.600000024, Offset: 0.0}
      Room: {Max: 0.400000006, Offset: 0.0, OffsetValue: 1.0}
  Type4:
    Curve:
      Direct: {Max: 0.200000003, Offset: 0.0, OffsetValue: 1.0}
      Filter1: {Max: 0.800000012, Offset: 0.0}
      Room: {Max: 0.200000003, Offset: 0.0, OffsetValue: 1.0}
  Type5:
    Curve:
      Direct: {Max: 0.00999999978, Offset: 0.0, OffsetValue: 1.0}
      Filter1: {Max: 1.0, Offset: 0.0}
      Room: {Max: 0.00999999978, Offset: 0.0, OffsetValue: 1.0}
  Type6:
    Curve:
      Direct: {Max: 0.0, Offset: 0.0, OffsetValue: 1.0}
      Filter1: {Max: 0.0, Offset: 0.0}
      Room: {Max: 0.0, Offset: 0.0, OffsetValue: 1.0}
  Type7:
    Curve:
      Direct: {Max: 0.0, Offset: 0.0, OffsetValue: 1.0}
      Filter1: {Max: 0.0, Offset: 0.0}
      Room: {Max: 0.0, Offset: 0.0, OffsetValue: 1.0}
