List:
  SB:
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_001.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_008.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road008.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_013.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road013.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_018.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road018.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_022.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road022.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_TamourHatago002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/TamourHatago002.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good01}
  T:
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked02_002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Attacked02_002.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_005.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_005.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_008.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_008.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_009.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_009.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Bad03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_010.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_010.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_011.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_011.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_GerudoCanyon002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_GerudoCanyon002.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Lanayru003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Lanayru003.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper004.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper005.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper005.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper006.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper006.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Bad01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper007.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper007.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Bad00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper008.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper008.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper012.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper012.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper013.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper013.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NorthHateru_around001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NorthHateru_around001.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Remains_Fancier001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Remains_Fancier001_02.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal04}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_009.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road009.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_010.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road010.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_016.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road016.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_045.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road045.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_WellMania.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_WellMania.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal04}
  U:
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_HatenoRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_HatenoRoad_AncientAssistant.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_KarakaraRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_KarakaraRoad_AncientAssistant.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_RidgeRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_RidgeRoad_AncientAssistant.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_TabanthaRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_TabanthaRoad_AncientAssistant.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_VolcanicRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_VolcanicRoad_AncientAssistant.game__component__UMiiParam.gyml,
    Voice: Hylia_Woman_Young_Normal04}
