{CavePalette: Work/WorldMgr/CavePalette/Cave_GerudoDesert_0009.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  FluidEffectType: FluidEffect_Cave_DustGroundOnly, IsNotAutoPlace: true, IsNotAutoSpawn: true, NameID: Work/Location/GerudoUndergroundTown.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
