{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: true, IsNotAutoSpawn: true,
  NameID: Work/Location/Cave_CentralHyrule_0017.game__location__Location.gyml, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
