AlwaysClient: false
AlwaysConsiderRanged: false
Attributes: []
MakesPlayerPartySizeInfinite: true
MaxAttackers: 3
PartyCreateRules: []
PartyDisbandRules: []
PartyJoinRules: [TargetCheck]
PartyMergeRules: []
PartyRadius: 10.0
PartySplitRules: []
TargetingRules: []
UniqueTag: None
