{CavePalette: Work/WorldMgr/CavePalette/HyruleWell.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  FluidEffectLightHeightLimit: 5.0, IsSmallCave: true, NameID: Work/Location/Well_0053.game__location__Location.gyml}
