{CavePalette: Work/WorldMgr/CavePalette/HebraFrost.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_Hebra_0023.game__location__Location.gyml,
  Temperature_DayAdd: 0.0, Temperature_DayDirect: 15.0, Temperature_NightDirect: 15.0}
