AlwaysClient: true
AlwaysConsiderRanged: false
Attributes: []
MakesPlayerPartySizeInfinite: false
MaxAttackers: -1
PartyCreateRules: [Always]
PartyDisbandRules: []
PartyJoinRules: []
PartyMergeRules: []
PartyRadius: 20.0
PartySplitRules: []
TargetingRules: []
UniqueTag: Player
