CavePalette: Work/WorldMgr/CavePalette/Eldin_Light.game__wm__CavePalette.gyml
EffectCaveFadeEndDistance: 60.0
EffectCaveFadeStartDistance: 30.0
EnvEffect: Invalid
EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml
EnvPaletteChangeSpeed: VeryFast
FluidEffectType: FluidEffect_Cave_Volcano
IsNotAutoPlace: false
IsNotAutoSpawn: false
IsNotAutoSpawn_Enemy: true
NameID: Work/Location/Cave_Eldin_0038.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
