List:
  SB:
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_DeathMt001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/DeathMt001.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewVolcanicRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewVolcanicRoad_AncientAssistantNormal.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal04}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_005.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road005.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Good03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_024.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road024.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_037.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road037.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_040.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road040.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad01}
  T:
  - {ControllerSet: Work/Phive/ControllerSetParam/NPC_oasis004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/oasis004.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/NPC_oasis004_fr03.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/NPC_oasis004_fr03.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked02_001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Attacked02_001.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal05}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked02_003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Attacked02_003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked02_004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Attacked02_004.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_004.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_CaveTraveler001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_CaveTraveler001.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_DeathEastHatago_002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/DeathEastHatago_002.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_FaronWoods007.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/FaronWoods007.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_FaronWoods008.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/FaronWoods008.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal04}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_FaronWoods009.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/FaronWoods009.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_FirstColony004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/FirstColony004.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Good01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_HatenoGate003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_HatenoGate003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_HyrulePlain006.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/HyrulePlain006.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_HyruleWestHatago002_Road.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_HyruleWestHatago002_Road.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Kakariko_Road_019.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road019.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Good03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper001.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper002.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper009.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper009.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NewsPaper011.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_NewsPaper011.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_NorthHateru005.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/NorthHateru005.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal04}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_OasisHylia_002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_OasisHylia_002.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_RitoHatago003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/RitoHatago003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road001.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road002.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road004.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_006.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road006.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal05}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_014.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road014.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_017.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road017.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_020.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road020.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal04}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_021.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road021.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_025.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road025.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_030.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road030.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_033.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road_033.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_044.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road044.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_SmallOasis005.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/SmallOasis005.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_SmallOasis006.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/SmallOasis006.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_SouthernVillage016.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/SouthernVillage016.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_TabantaHatago003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/TabantaHatago003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_TamourHatago2_001.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/TamourHatago2_001.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/subchallnpc000.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/subchallnpc000.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/subchallnpc000_twin.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/subchallnpc000_twin.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good00}
  U:
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_002.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Attacked_002_Scholar.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_006.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_006.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal05}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_007.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_007.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal03}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Attacked_012.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Attacked_012.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal04}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_BaseCamp008.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_BaseCamp008.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_BaseCampSoldier_Hylia004.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_BaseCampSoldier_Hylia004.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_FaronWoods006.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/FaronWoods006.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Normal02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_FutagoRoad_AncientAssistant.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_FutagoRoad_AncientAssistant.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_003.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road003.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_023.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road023.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_026.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road026.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal01}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_034.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Road_034.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Normal00}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_035.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Road035.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Middle_Bad02}
  - {ControllerSet: Work/Phive/ControllerSetParam/Npc_Road_036.phive__ControllerSetParam.gyml, Umii: Work/Component/UMiiParam/Npc_Road_036.game__component__UMiiParam.gyml,
    Voice: Hylia_Man_Young_Good00}
