{CavePalette: Work/WorldMgr/CavePalette/GerudoDesert_Light.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  EnvPaletteChangeSpeed: VeryFast, FluidEffectType: FluidEffect_Cave_DustGroundOnly, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_GerudoDesert_0045.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
