{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, FluidEffectType: FluidEffect_Cave_Dust,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, NameID: Work/Location/Cave_GerudoDesert_0036.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
