{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Normal, IsNotAutoPlace: false,
  IsSmallCave: true, NameID: Work/Location/Well_0002.game__location__Location.gyml, Temperature_DayDirect: 100.0, Temperature_NightDirect: 100.0}
