{CaveDarkEndDistance: 50.0, CaveDarkStartDistance: 30.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  FluidEffectType: FluidEffect_Cave_WhiteMistDark_ShortenRaycast, IsNotAutoPlace: true, IsNotAutoSpawn: true, NameID: Work/Location/Cave_CentralHyrule_0019.game__location__Location.gyml}
