{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, IsNotAutoSpawn: false,
  IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_HateruEast_0002.game__location__Location.gyml, Weather: CaveRain}
