{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Fast, FluidEffectType: FluidEffect_Cave_Volcano,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_Eldin_0037.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
