Distance:
- {LayerIndex: 0, LoadDistance: 1500.0, X: 50, Z: 9}
- {LoadDistance: 500.0, X: 30, Z: 12}
- {LoadDistance: 500.0, X: 30, Z: 11}
- {LoadDistance: 550.0, X: 43, Z: 40}
- {LoadDistance: 600.0, X: 54, Z: 40}
- {LoadDistance: 500.0, X: 11, Z: 34}
- {LoadDistance: 400.0, X: 9, Z: 32}
Extra:
- {LoadDistance: 500.0, Name: LDT, X: 3, Z: 58}
- {LoadDistance: 500.0, Name: LDT, X: 2, Z: 59}
- {LoadDistance: 500.0, Name: LDT, X: 3, Z: 59}
- {LoadDistance: 500.0, Name: LDT, X: 4, Z: 59}
- {LoadDistance: 500.0, Name: LDT, X: 5, Z: 59}
- {LoadDistance: 500.0, Name: LDT, X: 1, Z: 60}
- {LoadDistance: 500.0, Name: LDT, X: 2, Z: 60}
- {LoadDistance: 500.0, Name: LDT, X: 3, Z: 60}
- {LoadDistance: 500.0, Name: LDT, X: 4, Z: 60}
- {LoadDistance: 500.0, Name: LDT, X: 5, Z: 60}
- {LoadDistance: 500.0, Name: LDT, X: 2, Z: 61}
- {LoadDistance: 500.0, Name: LDT, X: 3, Z: 61}
- {LoadDistance: 500.0, Name: LDT, X: 4, Z: 61}
- {LoadDistance: 500.0, Name: LDT, X: 5, Z: 61}
- {LoadDistance: 500.0, Name: LDT, X: 3, Z: 62}
- {LoadDistance: 500.0, Name: LDT, X: 4, Z: 62}
- {LayerIndex: 0, LoadDistance: 1000.0, Name: LDF, X: 50, Z: 8}
- {LayerIndex: 0, LoadDistance: 1000.0, Name: LDF, X: 50, Z: 9}
- {LayerIndex: 0, LoadDistance: 1000.0, Name: LDF, X: 50, Z: 10}
Ground:
- {SplitHeight: 362.0, X: 37, Z: 23}
- {SplitHeight: 1586.0, X: 17, Z: 7}
- {SplitHeight: 1220.0, X: 75, Z: 38}
- {SplitHeight: 1818.0, X: 66, Z: 26}
- {SplitHeight: 860.0, X: 41, Z: 15}
- {SplitHeight: 1936.0, X: 58, Z: 46}
- {SplitHeight: 1088.0, X: 25, Z: 59}
- {SplitHeight: 495.0, X: 77, Z: 2}
- {SplitHeight: 1226.0, X: 76, Z: 38}
- {SplitHeight: 1518.0, X: 43, Z: 44}
- {SplitHeight: 1256.0, X: 21, Z: 24}
- {SplitHeight: 568.0, X: 51, Z: 58}
- {SplitHeight: 1164.0, X: 33, Z: 3}
- {SplitHeight: 862.0, X: 47, Z: 55}
- {SplitHeight: 1556.0, X: 43, Z: 38}
- {SplitHeight: 1538.0, X: 45, Z: 42}
- {SplitHeight: 1430.0, X: 67, Z: 26}
- {SplitHeight: 336.0, X: 38, Z: 23}
- {SplitHeight: 908.0, X: 29, Z: 44}
- {SplitHeight: 192.0, X: 37, Z: 25}
- {SplitHeight: 862.0, X: 41, Z: 16}
- {SplitHeight: 1153.0, X: 25, Z: 60}
- {SplitHeight: 1580.0, X: 17, Z: 8}
- {SplitHeight: 1506.0, X: 43, Z: 45}
- {SplitHeight: 1628.0, X: 46, Z: 42}
- {SplitHeight: 1142.0, X: 33, Z: 4}
- {SplitHeight: 2000.0, X: 12, Z: 34}
- {SplitHeight: 1520.0, X: 43, Z: 40}
- {SplitHeight: 876.0, X: 48, Z: 56}
Underground:
- {SplitHeight: -618.0, X: 50, Z: 9}
- {SplitHeight: -632.0, X: 50, Z: 58}
- {SplitHeight: -412.0, X: 45, Z: 51}
- {SplitHeight: -356.0, X: 76, Z: 60}
- {SplitHeight: -716.0, X: 57, Z: 6}
- {SplitHeight: -500.0, X: 39, Z: 12}
- {SplitHeight: -356.0, X: 57, Z: 47}
- {SplitHeight: -404.0, X: 44, Z: 49}
- {SplitHeight: -398.0, X: 30, Z: 42}
- {SplitHeight: -438.0, X: 33, Z: 47}
- {SplitHeight: -700.0, X: 50, Z: 11}
- {SplitHeight: -1195.0, X: 37, Z: 23}
- {SplitHeight: -1124.0, X: 37, Z: 25}
