{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Slow, IsNotAutoPlace: false,
  IsNotAutoSpawn: false, IsNotAutoSpawn_Animal: false, IsNotAutoSpawn_Enemy: false, IsNotAutoSpawn_Falling: false, NameID: Work/Location/Cave_HateruWest_0005.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
