{CavePalette: Work/WorldMgr/CavePalette/HyruleWell.game__wm__CavePalette.gyml, FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly,
  IsNotAutoPlace: false, IsSmallCave: true, NameID: Work/Location/Well_0014.game__location__Location.gyml, Temperature_DayDirect: 20.0,
  Temperature_NightDirect: 20.0}
