{EnvEffect: Invalid, EnvFireLevel: 1, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: VeryFast,
  FluidEffectType: FluidEffect_Cave_Volcano, IsNotAutoPlace: true, IsNotAutoSpawn: true, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
