{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, NameID: Work/Location/Cave_Lanayru_0048.game__location__Location.gyml,
  Weather: CaveRain}
