{EffectCaveFadeEndDistance: 25.0, EffectCaveFadeStartDistance: 10.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_LanayruMountain_0025.game__location__Location.gyml}
