{CavePalette: Work/WorldMgr/CavePalette/Eldin_Light.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsSmallCave: true, NameID: Work/Location/Well_0052.game__location__Location.gyml}
