{EffectCaveFadeEndDistance: 30.0, EffectCaveFadeStartDistance: 20.0, FluidEffectType: FluidEffect_Cave_Dust, NameID: Work/Location/Cave_GerudoDesert_0051.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
