{CavePalette: Work/WorldMgr/CavePalette/Cave_CentralHyrule_0027.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  EnvPaletteChangeSpeed: Normal, FluidEffectType: FluidEffect_Cave_WhiteMist_HighPrecision, IsNotAutoPlace: true, IsNotAutoSpawn: true,
  NameID: Work/Location/StartPoint_WakeupAltar.game__location__Location.gyml}
