{IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true, IsSmallCave: true, NameID: Work/Location/Well_0017.game__location__Location.gyml,
  NotEnemySearch: true, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
