{EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml, IsDeepHole: true, IsNotAutoPlace: true,
  IsNotAutoPlace_All: true, IsNotAutoSpawn: true, NameID: Work/Location/DeepHole_HyruleCastle.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
