{EffectCaveFadeEndDistance: 30.0, EffectCaveFadeStartDistance: 20.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, IsNotAutoSpawn_Animal: true, IsNotAutoSpawn_Bird: true, IsNotAutoSpawn_Enemy: true,
  IsNotAutoSpawn_Falling: true, NameID: Work/Location/Cave_HyruleForest_0007.game__location__Location.gyml}
