AlwaysClient: false
AlwaysConsiderRanged: false
Attributes: []
MakesPlayerPartySizeInfinite: false
MaxAttackers: 3
PartyCreateRules: [Always]
PartyDisbandRules: []
PartyJoinRules: [TargetCheck, DistanceCheck]
PartyMergeRules: [HigherPriority, Overlap]
PartyRadius: 5.0
PartySplitRules: [DistanceCheck]
TargetingRules: []
UniqueTag: None
