{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, IsNotAutoSpawn: false,
  NameID: Work/Location/Cave_Firone_0009.game__location__Location.gyml}
