{EffectCaveFadeEndDistance: 20.0, EffectCaveFadeStartDistance: 5.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, NameID: Work/Location/Cave_Lanayru_0019.game__location__Location.gyml, Weather: CaveRain}
