AlwaysClient: false
AlwaysConsiderRanged: false
Attributes: []
MakesPlayerPartySizeInfinite: false
MaxAttackers: 1
PartyCreateRules: [Always]
PartyDisbandRules: []
PartyJoinRules: [TargetCheck, MemoryCheck]
PartyMergeRules: [MemoryCheck, HigherPriority]
PartyRadius: 0.0
PartySplitRules: []
TargetingRules: []
UniqueTag: None
