EnvEffect: Invalid
EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml
EnvPaletteChangeSpeed: VeryFast
FluidEffectType: FluidEffect_Cave_Volcano
IsNotAutoPlace: false
IsNotAutoSpawn: false
IsNotAutoSpawn_Animal: true
IsNotAutoSpawn_Enemy: true
IsNotAutoSpawn_Falling: true
IsNotAutoSpawn_Material: true
NameID: Work/Location/Cave_Eldin_0026.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
