CavePalette: Work/WorldMgr/CavePalette/Eldin_Light.game__wm__CavePalette.gyml
EnvEffect: Invalid
EnvFireLevel: 1
EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml
EnvPaletteChangeSpeed: VeryFast
FluidEffectType: FluidEffect_Cave_Volcano
IsNotAutoPlace: false
IsNotAutoSpawn: false
NameID: Work/Location/Cave_Eldin_0033.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
