{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: true, IsNotAutoSpawn: true,
  NameID: Work/Location/Cave_CentralHyrule_0011.game__location__Location.gyml, Temperature_DayDirect: 15.0, Temperature_NightDirect: 15.0}
