{EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml, IsDeepHole: true, IsNotAutoPlace: true,
  IsNotAutoPlace_All: true, IsNotAutoSpawn: true, NameID: Work/Location/DeepHole_B-6_Tower.game__location__Location.gyml}
