{EffectCaveFadeEndDistance: 25.0, EffectCaveFadeStartDistance: 15.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  NameID: Work/Location/Cave_HateruWest_0008.game__location__Location.gyml, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
