{EffectCaveFadeEndDistance: 50.0, EffectCaveFadeStartDistance: 30.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_LanayruMountain_0026.game__location__Location.gyml}
