CavePalette: Work/WorldMgr/CavePalette/Default.game__wm__CavePalette.gyml
EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml
FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly
IsNotAutoPlace: false
IsNotAutoSpawn: false
IsNotAutoSpawn_Animal: false
IsNotAutoSpawn_Enemy: true
IsNotAutoSpawn_Falling: false
IsNotAutoSpawn_Insect: true
NameID: Work/Location/Cave_Lanayru_0036.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
