{EffectCaveFadeEndDistance: 35.0, EffectCaveFadeStartDistance: 20.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  EnvPaletteChangeSpeed: Normal, FluidEffectType: FluidEffect_Cave_Dust, IsNotAutoPlace: false, NameID: Work/Location/Cave_GerudoDesert_0008.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
