{EffectCaveFadeEndDistance: 15.0, EffectCaveFadeStartDistance: 5.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_Akkala_0007.game__location__Location.gyml}
