{EffectCaveFadeEndDistance: 40.0, EffectCaveFadeStartDistance: 25.0, EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml,
  IsDeepHole: true, IsNotAutoPlace: true, IsNotAutoPlace_All: true, IsNotAutoSpawn: true, NameID: Work/Location/DeepHole_ImeruMt.game__location__Location.gyml}
