Heaps:
  AI: {Size: 1980}
  AS: {Size: 128}
  Actor: {Size: 466944}
  ActorInstanceHeap: {Parent: Actor, Size: 385024}
  AdditionalTexHeapForDevelop: {Parent: DebugHeap, Size: 51200}
  AglWork: {Parent: Graphics, Size: 5120}
  Bake: {Size: 19888}
  Banc: {Size: 1024}
  Blackboard: {Size: 15}
  Camera: {Size: 2}
  Cave: {Size: 17920}
  Challenge: {Size: 1800}
  Controller: {Size: 25}
  DLogBuffer: {Parent: DebugLogger, Size: 32768}
  DLogDataStore: {Parent: DebugLogger, Size: 4096}
  DebugHeap: {Size: 0}
  DebugLogger: {Parent: DebugHeap, Size: 36864}
  DyingMessage: {Size: 8}
  DynamicTextureAllocatorMem: {Parent: Graphics, Size: 113664}
  EQS: {Size: 64}
  Effect: {Size: 26368}
  Event: {Size: 20480}
  Forest: {Size: 9600}
  GameCamera: {Size: 16}
  GameData: {Size: 12288}
  GameDataMgrInitDataDebug: {Parent: DebugHeap, Size: 7168}
  GamePlayReport: {Size: 0}
  GameSound: {Size: 96}
  GameTerrain: {Size: 297984}
  GameUI: {Size: 11572}
  GameUIUpdate0: {Size: 1}
  GameUIUpdate1: {Size: 1}
  GameXLink: {Size: 128}
  Graphics: {Size: 201728}
  LOD: {Size: 4}
  Malloc: {Parent: Reserved, Size: 11264}
  MaxDisplayListSize: {Parent: Graphics, Size: 4096}
  ModelResourceMgrGpuHeap: {Parent: ゲームグラフィックス, Size: 12288}
  ModelWorkBuffer: {Parent: Graphics, Size: 1200}
  ModuleSystem: {Size: 1887}
  MountRomCache: {Parent: ReservedInFramework, Size: 15360}
  NavMeshSystem: {Size: 1546}
  NvInitializeGraphics: {Parent: ReservedByFramework, Size: 16384}
  Perception: {Size: 3072}
  PhiveBackEnd: {Parent: Physics, Size: 63488}
  Physics: {Size: 71764}
  PlayReport: {Size: 1024}
  Program: {Parent: Reserved, Size: 99328}
  RSDB: {Size: 9728}
  Rail: {Size: 512}
  Reaction: {Size: 80}
  Reserved: {Size: -1}
  ReservedByFramework: {Parent: ReservedInFramework, Size: 43008}
  ReservedInFramework: {Parent: Reserved, Size: -1}
  Resource: {Size: 41984}
  ResourceDebug: {Parent: aresDebug, Size: 337920}
  ResourceDummyGeneralFormatParam: {Parent: Resource, Size: 1024}
  ResourceL: {Parent: Resource, Size: 0}
  ResourceS: {Parent: Resource, Size: 0}
  ResourceU: {Parent: Resource, Size: 0}
  Rumble: {Size: 515}
  SaveLoad: {Parent: Scene, Size: 3072}
  Scene: {Size: 16424}
  SceneHeapParent: {Parent: Scene, Size: 14528}
  Sound: {Size: 93184}
  System: {Size: 0}
  Terrain: {Size: 5}
  TextureCompactionWorkHeap: {Parent: ゲームグラフィックス, Size: 8192}
  TextureHeap: {Parent: ゲームグラフィックス, Size: 506880}
  Transceiver: {Size: 43}
  TransceiverExtraInfo: {Parent: Transceiver, Size: 26}
  UI: {Size: 45688}
  VirtualAddressMemory: {Parent: Reserved, Size: 1101824}
  VolumeStats: {Size: 800}
  XLink: {Size: 320}
  aresDebug: {Parent: DebugHeap, Size: 374784}
  カリング: {Size: 445}
  ケミカル: {Size: 3481}
  ゲームエフェクト: {Size: 128}
  ゲームグラフィックス: {Size: 571392}
  ゲームリアクション: {Size: 50}
  ゲーム物理: {Size: 80}
  ワールドマネージャ: {Size: 4352}
  特殊能力システム: {Size: 540}
  組立システム: {Size: 1600}
  草: {Size: 9318}
