CollisionReactionSettingPath: Work/Reaction/CollisionReactionSystemSetting/CollisionReactionSystemSetting.engine__reaction__CollisionReactionSystemSetting.gyml
EmitterPoolSize: 64
ExtendedSettingsPath: {HitReactionSetting: Work/Reaction/HitReactionSystemSetting/HitReactionSystemSetting.game__reaction__HitReactionSystemSetting.gyml}
PropertyDefinitions:
- {IsSetXLinkProperty: true, PropertyName: マテリアル, PropertyNameHash: !u 0xda6dbe1f, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: サブマテリアル, PropertyNameHash: !u 0xbbceaa63, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: サウンドマテリアル, PropertyNameHash: !u 0x36d712f9, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: 簡易サウンドマテリアル, PropertyNameHash: !u 0x7719c42d, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: サイズ, PropertyNameHash: !u 0xaf31d844, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: スケールタイプ, PropertyNameHash: !u 0xbe77a647, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: 地面の濡れ具合, PropertyNameHash: !u 0x3e959d28, PropertyType: F32}
- {IsSetXLinkProperty: true, PropertyName: 深さ(Rea), PropertyNameHash: !u 0xbe6d8413, PropertyType: F32}
- {IsSetXLinkProperty: true, PropertyName: 地形の角度, PropertyNameHash: !u 0x107a4b6d, PropertyType: F32}
- {IsSetXLinkProperty: true, PropertyName: 水の移動速度, PropertyNameHash: !u 0xc8c28d31, PropertyType: F32}
- {IsSetXLinkProperty: true, PropertyName: 水面投影面積, PropertyNameHash: !u 0x775a664a, PropertyType: F32}
- {IsSetXLinkProperty: true, PropertyName: ヒットリアクションタイプ, PropertyNameHash: !u 0xe39bc208, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: ヒットリアクション付加タイプ, PropertyNameHash: !u 0x4eb01f8e, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: 攻撃元マテリアル, PropertyNameHash: !u 0x5158b6cd, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: ケミカル, PropertyNameHash: !u 0xa4116e47, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: 攻撃元所属, PropertyNameHash: !u 0xcabce493, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: 攻撃先所属, PropertyNameHash: !u 0x174c1e55, PropertyType: Enum}
- {IsSetXLinkProperty: true, PropertyName: 体力, PropertyNameHash: !u 0x5ba1ecf5, PropertyType: F32}
- {PropertyName: 初期質量, PropertyNameHash: !u 0xbef81742, PropertyType: F32}
- {IsSetXLinkProperty: true, PropertyName: 水マテリアル, PropertyNameHash: !u 0x8a65b0d1, PropertyType: Enum}
ReactionActorList: [Work/Actor/ReactionHit.engine__actor__ActorParam.gyml, Work/Actor/ReactionField.engine__actor__ActorParam.gyml,
  Work/Actor/Chemical.engine__actor__ActorParam.gyml]
ReactionTypeList:
- Work/Reaction/ReactionTypeParam/Land.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/Drag.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/Roll.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/LandPropagation.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterIn.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterEnter.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterFloatUp.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterFloatDown.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterOut.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterExit.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterFloatMove.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterRotateIn.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/WaterRotateOut.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/RagdollLand.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/Hit.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/Lumbered.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/HoldOn.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/HoldOff.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/BondLoadIncrease.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/BondLoadWarning.engine__reaction__ReactionTypeParam.gyml
- Work/Reaction/ReactionTypeParam/ShieldSurfLand.engine__reaction__ReactionTypeParam.gyml
WaterReactionSettingPath: Work/Reaction/WaterReactionSystemSetting/WaterReactionSystemSetting.engine__reaction__WaterReactionSystemSetting.gyml
