{EffectCaveFadeEndDistance: 70.0, EffectCaveFadeStartDistance: 55.0, EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml,
  IsDeepHole: true, IsNotAutoPlace: true, IsNotAutoPlace_All: true, IsNotAutoSpawn: true, NameID: Work/Location/DeepHole_RirimukuMt.game__location__Location.gyml}
