{CaveDarkEndDistance: 200.0, CaveDarkStartDistance: 180.0, EffectCaveFadeEndDistance: 80.0, EffectCaveFadeStartDistance: 60.0,
  EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, FluidEffectType: FluidEffect_Cave_WhiteMistDark,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, NameID: Work/Location/Cave_HateruEast_0007.game__location__Location.gyml}
