{CavePalette: Work/WorldMgr/CavePalette/Cave_GerudoDesert_0039.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Gerudo_Cave.game__wm__ResEnvPalette.gyml,
  EnvPaletteChangeSpeed: Fast, FluidEffectType: FluidEffect_Cave_Dust_EnclosedSpace, IsNotAutoPlace: false, NameID: Work/Location/Cave_GerudoDesert_0039.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
