{EffectCaveFadeEndDistance: 20.0, EffectCaveFadeStartDistance: 10.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_Hebra_0030.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
