{EffectCaveFadeEndDistance: 45.0, EffectCaveFadeStartDistance: 35.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly, IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_HyruleForest_0001.game__location__Location.gyml}
