{EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml, FluidEffectType: None, IsDeepHole: true,
  IsDeepHoleInCave: true, IsNotAutoPlace: false, IsNotAutoPlace_All: true, IsNotAutoSpawn: true, NameID: Work/Location/DeepHole_Firone.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
