{CavePalette: Work/WorldMgr/CavePalette/FiloneRemains.game__wm__CavePalette.gyml, EffectCaveFadeEndDistance: 35.0, EffectCaveFadeStartDistance: 20.0,
  EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, IsNotAutoSpawn: false,
  NameID: Work/Location/Cave_Firone_0008.game__location__Location.gyml}
