{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: VeryFast, FluidEffectType: FluidEffect_Cave_Dust_EnclosedSpace,
  IsNotAutoPlace: false, NameID: Work/Location/Cave_GerudoDesert_0032.game__location__Location.gyml, Temperature_DayDirect: 20.0,
  Temperature_NightDirect: 20.0}
