CellList:
  DispOffReverseRecorder___AutoBuild: {$type: engine__effect__PauseConfigCell, ColumnKey: AutoBuild, IsDraw: true, RowKey: DispOffReverseRecorder}
  DispOffReverseRecorder___EventDebug: {$type: engine__effect__PauseConfigCell, ColumnKey: EventDebug, IsDraw: true, RowKey: DispOffReverseRecorder}
  DispOffReverseRecorder___Normal: {$type: engine__effect__PauseConfigCell, ColumnKey: Normal, IsCalc: true, IsDraw: true,
    RowKey: DispOffReverseRecorder}
  DispOffReverseRecorder___Pouch: {$type: engine__effect__PauseConfigCell, ColumnKey: Pouch, RowKey: DispOffReverseRecorder}
  DispOffReverseRecorder___ReverseRecorder: {$type: engine__effect__PauseConfigCell, ColumnKey: ReverseRecorder, RowKey: DispOffReverseRecorder}
  MoveBlueprint___AutoBuild: {$type: engine__effect__PauseConfigCell, ColumnKey: AutoBuild, IsCalc: true, IsDraw: true, RowKey: MoveBlueprint}
  MoveBlueprint___EventDebug: {$type: engine__effect__PauseConfigCell, ColumnKey: EventDebug, IsDraw: true, RowKey: MoveBlueprint}
  MoveBlueprint___Normal: {$type: engine__effect__PauseConfigCell, ColumnKey: Normal, IsCalc: true, IsDraw: true, RowKey: MoveBlueprint}
  MoveBlueprint___Pouch: {$type: engine__effect__PauseConfigCell, ColumnKey: Pouch, RowKey: MoveBlueprint}
  MoveBlueprint___ReverseRecorder: {$type: engine__effect__PauseConfigCell, ColumnKey: ReverseRecorder, IsDraw: true, RowKey: MoveBlueprint}
  MovePouchOnly___AutoBuild: {$type: engine__effect__PauseConfigCell, ColumnKey: AutoBuild, IsCalc: true, IsDraw: true, RowKey: MovePouchOnly}
  MovePouchOnly___EventDebug: {$type: engine__effect__PauseConfigCell, ColumnKey: EventDebug, IsDraw: true, RowKey: MovePouchOnly}
  MovePouchOnly___Normal: {$type: engine__effect__PauseConfigCell, ColumnKey: Normal, IsCalc: true, RowKey: MovePouchOnly}
  MovePouchOnly___Pouch: {$type: engine__effect__PauseConfigCell, ColumnKey: Pouch, IsCalc: true, IsDraw: true, RowKey: MovePouchOnly}
  MovePouchOnly___ReverseRecorder: {$type: engine__effect__PauseConfigCell, ColumnKey: ReverseRecorder, IsCalc: true, IsDraw: true,
    RowKey: MovePouchOnly}
  MovePouch___AutoBuild: {$type: engine__effect__PauseConfigCell, ColumnKey: AutoBuild, IsCalc: true, IsDraw: true, RowKey: MovePouch}
  MovePouch___EventDebug: {$type: engine__effect__PauseConfigCell, ColumnKey: EventDebug, IsDraw: true, RowKey: MovePouch}
  MovePouch___Normal: {$type: engine__effect__PauseConfigCell, ColumnKey: Normal, IsCalc: true, IsDraw: true, RowKey: MovePouch}
  MovePouch___Pouch: {$type: engine__effect__PauseConfigCell, ColumnKey: Pouch, IsCalc: true, IsDraw: true, RowKey: MovePouch}
  MovePouch___ReverseRecorder: {$type: engine__effect__PauseConfigCell, ColumnKey: ReverseRecorder, IsCalc: true, IsDraw: true,
    RowKey: MovePouch}
  MoveReverseRecorder___AutoBuild: {$type: engine__effect__PauseConfigCell, ColumnKey: AutoBuild, IsDraw: true, RowKey: MoveReverseRecorder}
  MoveReverseRecorder___EventDebug: {$type: engine__effect__PauseConfigCell, ColumnKey: EventDebug, IsDraw: true, RowKey: MoveReverseRecorder}
  MoveReverseRecorder___Normal: {$type: engine__effect__PauseConfigCell, ColumnKey: Normal, IsCalc: true, IsDraw: true, RowKey: MoveReverseRecorder}
  MoveReverseRecorder___Pouch: {$type: engine__effect__PauseConfigCell, ColumnKey: Pouch, RowKey: MoveReverseRecorder}
  MoveReverseRecorder___ReverseRecorder: {$type: engine__effect__PauseConfigCell, ColumnKey: ReverseRecorder, IsCalc: true,
    IsDraw: true, RowKey: MoveReverseRecorder}
  Normal___AutoBuild: {$type: engine__effect__PauseConfigCell, ColumnKey: AutoBuild, IsDraw: true, RowKey: Normal}
  Normal___EventDebug: {$type: engine__effect__PauseConfigCell, ColumnKey: EventDebug, IsDraw: true, RowKey: Normal}
  Normal___Normal: {$type: engine__effect__PauseConfigCell, ColumnKey: Normal, IsCalc: true, IsDraw: true, RowKey: Normal}
  Normal___Pouch: {$type: engine__effect__PauseConfigCell, ColumnKey: Pouch, IsCalc: false, RowKey: Normal}
  Normal___ReverseRecorder: {$type: engine__effect__PauseConfigCell, ColumnKey: ReverseRecorder, IsDraw: true, RowKey: Normal}
TableType: Work/System/CombinationDataTable/engine__effect__PauseConfig.pp__CombinationDataTable.gyml
