{EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml, IsDeepHole: true, IsEnableEnv: true,
  IsNotAutoPlace: true, IsNotAutoPlace_All: true, IsNotAutoSpawn: true, IsNotAutoSpawn_Enemy: true, IsNotAutoSpawn_Falling: false}
