EffectCaveFadeEndDistance: 200.0
EffectCaveFadeStartDistance: 100.0
EnvEffect: Invalid
EnvFireLevel: 1
EnvPalette: Work/WorldMgr/ResEnvPalette/MainField_Underground.game__wm__ResEnvPalette.gyml
IsDeepHole: true
IsNotAutoPlace: true
IsNotAutoPlace_All: true
IsNotAutoSpawn: true
NameID: Work/Location/DeepHole_DeathMountain.game__location__Location.gyml
Temperature_DayDirect: 20.0
Temperature_NightDirect: 20.0
