{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly,
  IsNotAutoPlace: false, IsNotAutoSpawn: false, NameID: Work/Location/Cave_HateruEast_0009.game__location__Location.gyml,
  Weather: CaveRain}
