{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, IsNotAutoSpawn: false,
  NameID: '', Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
