{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Normal, FluidEffectType: FluidEffect_Cave_WhiteMistDark,
  IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true, NameID: Work/Location/Cave_HyruleForest_0008.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0, Weather: Invalid}
