{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsConnectDeepHole: true, IsNotAutoPlace: false,
  IsNotAutoSpawn: false, NameID: Work/Location/Cave_Lanayru_0061.game__location__Location.gyml, Temperature_DayDirect: 20.0,
  Temperature_NightDirect: 20.0, Weather: CaveRain}
