{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true,
  NameID: Work/Location/Cave_Hebra_0036.game__location__Location.gyml}
