{EffectCaveFadeEndDistance: 10.0, EffectCaveFadeStartDistance: 0.0, IsNotAutoPlace: false, IsSmallCave: true, NameID: Work/Location/Well_0031.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
