{$parent: Work/Component/CaveEnvironmentParam/DeepHole_Standard.game__component__CaveEnvironmentParam.gyml, EffectCaveFadeEndDistance: 60.0,
  EffectCaveFadeStartDistance: 30.0, NameID: Work/Location/DeepHole_Higakkare.game__location__Location.gyml}
