{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsNotAutoSpawn_Enemy: true, IsSmallCave: true,
  NameID: Work/Location/Well_0045.game__location__Location.gyml, Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
