CellList:
  Camera___Avoid: {$type: engine__framework__SpStepRateCell, ColumnKey: Avoid, RowKey: Camera}
  Camera___AvoidAttack: {$type: engine__framework__SpStepRateCell, ColumnKey: AvoidAttack, RowKey: Camera}
  Camera___Bow: {$type: engine__framework__SpStepRateCell, ColumnKey: Bow, RowKey: Camera}
  Camera___DragonDarkness: {$type: engine__framework__SpStepRateCell, ColumnKey: DragonDarkness, RowKey: Camera, SpStepRate: 0.0500000007}
  Camera___EventSlow1: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow1, RowKey: Camera, SpStepRate: 0.100000001}
  Camera___EventSlow2: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow2, RowKey: Camera, SpStepRate: 0.0500000007}
  Camera___EventSlow3: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow3, RowKey: Camera, SpStepRate: 0.200000003}
  Camera___EventSlow4: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow4, RowKey: Camera, SpStepRate: 0.5}
  Camera___GanondorfAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: GanondorfAvoid, RowKey: Camera, SpStepRate: 1.0}
  Camera___Guard: {$type: engine__framework__SpStepRateCell, ColumnKey: Guard, RowKey: Camera}
  Camera___HitStop: {$type: engine__framework__SpStepRateCell, ColumnKey: HitStop, RowKey: Camera}
  Camera___PreAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: PreAvoid, RowKey: Camera}
  Camera___RaumiGuard: {$type: engine__framework__SpStepRateCell, ColumnKey: RaumiGuard, RowKey: Camera}
  Camera___ReverseRecorder: {$type: engine__framework__SpStepRateCell, ColumnKey: ReverseRecorder, RowKey: Camera}
  Camera___Scope: {$type: engine__framework__SpStepRateCell, ColumnKey: Scope, RowKey: Camera}
  Camera___Shattered: {$type: engine__framework__SpStepRateCell, ColumnKey: Shattered, RowKey: Camera}
  Camera___ThinFilmBoardHit: {$type: engine__framework__SpStepRateCell, ColumnKey: ThinFilmBoardHit, RowKey: Camera}
  Cloth___Avoid: {$type: engine__framework__SpStepRateCell, ColumnKey: Avoid, RowKey: Cloth}
  Cloth___AvoidAttack: {$type: engine__framework__SpStepRateCell, ColumnKey: AvoidAttack, RowKey: Cloth}
  Cloth___Bow: {$type: engine__framework__SpStepRateCell, ColumnKey: Bow, RowKey: Cloth}
  Cloth___DragonDarkness: {$type: engine__framework__SpStepRateCell, ColumnKey: DragonDarkness, RowKey: Cloth}
  Cloth___EventSlow1: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow1, RowKey: Cloth, SpStepRate: 0.100000001}
  Cloth___EventSlow2: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow2, RowKey: Cloth, SpStepRate: 0.0500000007}
  Cloth___EventSlow3: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow3, RowKey: Cloth, SpStepRate: 0.200000003}
  Cloth___EventSlow4: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow4, RowKey: Cloth, SpStepRate: 0.5}
  Cloth___GanondorfAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: GanondorfAvoid, RowKey: Cloth}
  Cloth___Guard: {$type: engine__framework__SpStepRateCell, ColumnKey: Guard, RowKey: Cloth}
  Cloth___HitStop: {$type: engine__framework__SpStepRateCell, ColumnKey: HitStop, RowKey: Cloth}
  Cloth___PreAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: PreAvoid, RowKey: Cloth}
  Cloth___RaumiGuard: {$type: engine__framework__SpStepRateCell, ColumnKey: RaumiGuard, RowKey: Cloth}
  Cloth___ReverseRecorder: {$type: engine__framework__SpStepRateCell, ColumnKey: ReverseRecorder, RowKey: Cloth}
  Cloth___Scope: {$type: engine__framework__SpStepRateCell, ColumnKey: Scope, RowKey: Cloth}
  Cloth___Shattered: {$type: engine__framework__SpStepRateCell, ColumnKey: Shattered, RowKey: Cloth}
  Cloth___ThinFilmBoardHit: {$type: engine__framework__SpStepRateCell, ColumnKey: ThinFilmBoardHit, RowKey: Cloth}
  DeathTimer___Avoid: {$type: engine__framework__SpStepRateCell, ColumnKey: Avoid, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___AvoidAttack: {$type: engine__framework__SpStepRateCell, ColumnKey: AvoidAttack, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___Bow: {$type: engine__framework__SpStepRateCell, ColumnKey: Bow, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___DragonDarkness: {$type: engine__framework__SpStepRateCell, ColumnKey: DragonDarkness, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___EventSlow1: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow1, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___EventSlow2: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow2, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___EventSlow3: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow3, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___EventSlow4: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow4, RowKey: DeathTimer, SpStepRate: 0.5}
  DeathTimer___GanondorfAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: GanondorfAvoid, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___Guard: {$type: engine__framework__SpStepRateCell, ColumnKey: Guard, RowKey: DeathTimer, SpStepRate: 1.0}
  DeathTimer___HitStop: {$type: engine__framework__SpStepRateCell, ColumnKey: HitStop, RowKey: DeathTimer, SpStepRate: 1.0}
  DeathTimer___PreAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: PreAvoid, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___RaumiGuard: {$type: engine__framework__SpStepRateCell, ColumnKey: RaumiGuard, RowKey: DeathTimer, SpStepRate: 1.0}
  DeathTimer___ReverseRecorder: {$type: engine__framework__SpStepRateCell, ColumnKey: ReverseRecorder, RowKey: DeathTimer,
    SpStepRate: 0.349999994}
  DeathTimer___Scope: {$type: engine__framework__SpStepRateCell, ColumnKey: Scope, RowKey: DeathTimer, SpStepRate: 0.349999994}
  DeathTimer___Shattered: {$type: engine__framework__SpStepRateCell, ColumnKey: Shattered, RowKey: DeathTimer, SpStepRate: 1.0}
  DeathTimer___ThinFilmBoardHit: {$type: engine__framework__SpStepRateCell, ColumnKey: ThinFilmBoardHit, RowKey: DeathTimer,
    SpStepRate: 1.0}
  Default___Avoid: {$type: engine__framework__SpStepRateCell, ColumnKey: Avoid, RowKey: Default, SpStepRate: 0.0500000007}
  Default___AvoidAttack: {$type: engine__framework__SpStepRateCell, ColumnKey: AvoidAttack, RowKey: Default, SpStepRate: 0.0500000007}
  Default___Bow: {$type: engine__framework__SpStepRateCell, ColumnKey: Bow, RowKey: Default, SpStepRate: 0.0500000007}
  Default___DragonDarkness: {$type: engine__framework__SpStepRateCell, ColumnKey: DragonDarkness, RowKey: Default, SpStepRate: 0.0500000007}
  Default___EventSlow1: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow1, RowKey: Default, SpStepRate: 0.100000001}
  Default___EventSlow2: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow2, RowKey: Default, SpStepRate: 0.0500000007}
  Default___EventSlow3: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow3, RowKey: Default, SpStepRate: 0.200000003}
  Default___EventSlow4: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow4, RowKey: Default, SpStepRate: 0.5}
  Default___GanondorfAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: GanondorfAvoid, RowKey: Default, SpStepRate: 0.0500000007}
  Default___Guard: {$type: engine__framework__SpStepRateCell, ColumnKey: Guard, RowKey: Default, SpStepRate: 0.100000001}
  Default___HitStop: {$type: engine__framework__SpStepRateCell, ColumnKey: HitStop, RowKey: Default, SpStepRate: 0.100000001}
  Default___PreAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: PreAvoid, RowKey: Default, SpStepRate: 0.0500000007}
  Default___RaumiGuard: {$type: engine__framework__SpStepRateCell, ColumnKey: RaumiGuard, RowKey: Default, SpStepRate: 0.100000001}
  Default___ReverseRecorder: {$type: engine__framework__SpStepRateCell, ColumnKey: ReverseRecorder, RowKey: Default, SpStepRate: 0.0500000007}
  Default___Scope: {$type: engine__framework__SpStepRateCell, ColumnKey: Scope, RowKey: Default, SpStepRate: 0.0500000007}
  Default___Shattered: {$type: engine__framework__SpStepRateCell, ColumnKey: Shattered, RowKey: Default, SpStepRate: 0.100000001}
  Default___ThinFilmBoardHit: {$type: engine__framework__SpStepRateCell, ColumnKey: ThinFilmBoardHit, RowKey: Default, SpStepRate: 0.100000001}
  Player___Avoid: {$type: engine__framework__SpStepRateCell, ColumnKey: Avoid, RowKey: Player, SpStepRate: 0.100000001}
  Player___AvoidAttack: {$type: engine__framework__SpStepRateCell, ColumnKey: AvoidAttack, RowKey: Player}
  Player___Bow: {$type: engine__framework__SpStepRateCell, ColumnKey: Bow, RowKey: Player}
  Player___DragonDarkness: {$type: engine__framework__SpStepRateCell, ColumnKey: DragonDarkness, RowKey: Player, SpStepRate: 0.0500000007}
  Player___EventSlow1: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow1, RowKey: Player, SpStepRate: 0.100000001}
  Player___EventSlow2: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow2, RowKey: Player, SpStepRate: 0.0500000007}
  Player___EventSlow3: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow3, RowKey: Player, SpStepRate: 0.200000003}
  Player___EventSlow4: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow4, RowKey: Player, SpStepRate: 0.5}
  Player___GanondorfAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: GanondorfAvoid, RowKey: Player, SpStepRate: 0.0500000007}
  Player___Guard: {$type: engine__framework__SpStepRateCell, ColumnKey: Guard, RowKey: Player, SpStepRate: 0.100000001}
  Player___HitStop: {$type: engine__framework__SpStepRateCell, ColumnKey: HitStop, RowKey: Player, SpStepRate: 0.100000001}
  Player___PreAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: PreAvoid, RowKey: Player}
  Player___RaumiGuard: {$type: engine__framework__SpStepRateCell, ColumnKey: RaumiGuard, RowKey: Player, SpStepRate: 0.100000001}
  Player___ReverseRecorder: {$type: engine__framework__SpStepRateCell, ColumnKey: ReverseRecorder, RowKey: Player, SpStepRate: 0.0500000007}
  Player___Scope: {$type: engine__framework__SpStepRateCell, ColumnKey: Scope, RowKey: Player}
  Player___Shattered: {$type: engine__framework__SpStepRateCell, ColumnKey: Shattered, RowKey: Player, SpStepRate: 0.100000001}
  Player___ThinFilmBoardHit: {$type: engine__framework__SpStepRateCell, ColumnKey: ThinFilmBoardHit, RowKey: Player, SpStepRate: 0.100000001}
  PouchActor___Avoid: {$type: engine__framework__SpStepRateCell, ColumnKey: Avoid, RowKey: PouchActor}
  PouchActor___AvoidAttack: {$type: engine__framework__SpStepRateCell, ColumnKey: AvoidAttack, RowKey: PouchActor}
  PouchActor___Bow: {$type: engine__framework__SpStepRateCell, ColumnKey: Bow, RowKey: PouchActor}
  PouchActor___DragonDarkness: {$type: engine__framework__SpStepRateCell, ColumnKey: DragonDarkness, RowKey: PouchActor}
  PouchActor___EventSlow1: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow1, RowKey: PouchActor}
  PouchActor___EventSlow2: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow2, RowKey: PouchActor}
  PouchActor___EventSlow3: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow3, RowKey: PouchActor}
  PouchActor___EventSlow4: {$type: engine__framework__SpStepRateCell, ColumnKey: EventSlow4, RowKey: PouchActor}
  PouchActor___GanondorfAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: GanondorfAvoid, RowKey: PouchActor}
  PouchActor___Guard: {$type: engine__framework__SpStepRateCell, ColumnKey: Guard, RowKey: PouchActor}
  PouchActor___HitStop: {$type: engine__framework__SpStepRateCell, ColumnKey: HitStop, RowKey: PouchActor}
  PouchActor___PreAvoid: {$type: engine__framework__SpStepRateCell, ColumnKey: PreAvoid, RowKey: PouchActor}
  PouchActor___RaumiGuard: {$type: engine__framework__SpStepRateCell, ColumnKey: RaumiGuard, RowKey: PouchActor}
  PouchActor___ReverseRecorder: {$type: engine__framework__SpStepRateCell, ColumnKey: ReverseRecorder, RowKey: PouchActor}
  PouchActor___Scope: {$type: engine__framework__SpStepRateCell, ColumnKey: Scope, RowKey: PouchActor}
  PouchActor___Shattered: {$type: engine__framework__SpStepRateCell, ColumnKey: Shattered, RowKey: PouchActor}
  PouchActor___ThinFilmBoardHit: {$type: engine__framework__SpStepRateCell, ColumnKey: ThinFilmBoardHit, RowKey: PouchActor}
TableType: Work/System/CombinationDataTable/engine__system__SpStepRateConfig.pp__CombinationDataTable.gyml
