{$parent: Work/Component/CaveEnvironmentParam/DeepHole_Standard.game__component__CaveEnvironmentParam.gyml, IsDeepHoleInCave: true,
  NameID: Work/Location/Cave_Lanayru_0063.game__location__Location.gyml, Weather: CaveRain}
