{CavePalette: Work/WorldMgr/CavePalette/HyruleWell.game__wm__CavePalette.gyml, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  FluidEffectType: FluidEffect_Cave_WhiteMistGroundOnly, IsNotAutoSpawn_Enemy: true, IsSmallCave: true, NameID: Work/Location/Well_0050.game__location__Location.gyml}
