{EffectCaveFadeEndDistance: 30.0, EffectCaveFadeStartDistance: 20.0, EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml,
  NameID: Work/Location/Cave_HateruWest_0012.game__location__Location.gyml}
