EntityMaterialDamageSettings:
- DamageAmount: 4
  DamageIntensity: Moderate
  DamageType: Spike
  IsIncludeAllMaterials: true
  IsUseStrongImpulseThreshold: true
  KnockbackIntensity: Strong
  SubMaterialValues: [31]
- DamageAmount: 1
  DamageIntensity: Weak
  DamageType: Spike
  IsIncludeAllMaterials: true
  IsIncludeAllSubMaterials: false
  IsUseStrongImpulseThreshold: true
  KnockbackIntensity: Normal
  SubMaterialValues: [32]
- DamageAmount: 12
  DamageIntensity: Moderate
  DamageType: EnergyWall
  IsIncludeAllMaterials: true
  KnockbackIntensity: Strong
  SubMaterialValues: [38]
- {IsCheckRelativeVelocity: true, IsIncludeAllMaterials: true, IsIncludeAllSubMaterials: true, IsUseNonImpulseContact: true}
MassThreshold: 300.0
MomentumThreshold: 2800.0
SpikeYMinusThreshold: 500.0
StrongImpulseThreshold: 2.0
VelocityThreshold: 2.79999995
