{CavePalette: Work/WorldMgr/CavePalette/Eldin_Light.game__wm__CavePalette.gyml, EnvEffect: Invalid, EnvFireLevel: 1, EnvPaletteChangeSpeed: VeryFast,
  IsNotAutoPlace: false, IsNotAutoSpawn_Enemy: true, IsSmallCave: true, NameID: Work/Location/Well_0033.game__location__Location.gyml,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
