{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, IsConnectDeepHole: true, IsNotAutoPlace: false,
  IsNotAutoSpawn: false, IsNotAutoSpawn_Animal: true, IsNotAutoSpawn_Bird: true, IsNotAutoSpawn_Enemy: true, IsNotAutoSpawn_Falling: true,
  Temperature_DayDirect: 20.0, Temperature_NightDirect: 20.0}
