{EnvPalette: Work/WorldMgr/ResEnvPalette/Cave_Normal.game__wm__ResEnvPalette.gyml, EnvPaletteChangeSpeed: Normal, IsConnectDeepHole: true,
  NameID: Work/Location/DeepHole_HyruleCastleEast.game__location__Location.gyml}
