{$parent: Work/Component/CaveEnvironmentParam/DeepHole_Standard.game__component__CaveEnvironmentParam.gyml, EffectCaveFadeEndDistance: 30.0,
  EffectCaveFadeStartDistance: 10.0, NameID: Work/Location/DeepHole_SanaePlateau.game__location__Location.gyml}
